server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  datasource:
    url: jdbc:mariadb://infodb.ansan.ac.kr:3306/db2451506_game_rental
    username: i2451506
    password: qkr#wkd#ghks
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
  jwt:
    secret: ae13fb186ac0aa56b38a3f03be57578f262bd7a4434beccbf2c5bbd3628ae2017bc713e565a6ebd139ed1430a29edab9324f88c604e44f3e5bf048ee99b8d1f3

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace