server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://infodb.ansan.ac.kr:3306/db2451506_game_rental
    username: i2451506
    password: welcome2ansan12!!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace